language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements_dev.txt

script:
  - source env.sh
  - pytest -s -vvv $TEST_PATH/test_dag_train_models

after_success:
  - bash <(curl -s https://codecov.io/bash)