version: '3.3'

services:

  postgres:
    image: postgres:11
    container_name: aura-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_AIRFLOW}

volumes:
  postgres-storage:
